# Generated by Django 5.0.1 on 2024-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('Lname', models.CharField(max_length=64)),
                ('sid', models.IntegerField()),
                ('gpa', models.PositiveIntegerField()),
            ],
        ),
    ]
