# Generated by Django 5.0.1 on 2024-03-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('precourses', models.CharField(max_length=64)),
                ('cid', models.IntegerField()),
            ],
        ),
    ]
