# Generated by Django 5.0.1 on 2024-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('Lname', models.CharField(max_length=64)),
                ('sid', models.IntegerField()),
                ('gpa', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cid',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='stud',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.course'),
        ),
    ]
